#ifndef DEFAULTS_H
#define DEFAULTS_H

#define DEFAULT_X_MAX_TRAVEL 200.0f
#define DEFAULT_Y_MAX_TRAVEL 200.0f
#define DEFAULT_Z_MAX_TRAVEL 200.0f

#define DEFAULT_HOMING_DIR_MASK 0
#define DEFAULT_HOMING_FEEDRATE 500.0f

#endif
